<a href="https://colab.research.google.com/github/LeeSeungwon89/Machine-learning_Theory/blob/master/CHAPTER9%20%EC%B6%94%EC%B2%9C%20%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 추천 시스템의 개요와 배경**

## **1.1. 추천 시스템의 개요**

본서를 참고하시기 바랍니다.

## **1.2. 온라인 스토어의 필수 요소, 추천 시스템**

추천 시스템은 온라인에서 매우 필수적인 기술입니다. 전자상거래, 콘텐츠 제공 등 다양한 온라인 업종에서 사용됩니다. 

아래 데이터는 추천 시스템을 구성하는 데 사용될 수 있습니다.

- 사용자가 무엇을 클릭했습니까?

- 사용자가 어떤 상품을 확인하거나 장바구니에 넣었습니까?

- 사용자가 어떤 상품을 구매했습니까?

- 사용자가 제품과 영화를 어떻게 평가했습니까?

- 사용자가 본인의 취향을 어떻게 정의했습니까?

이 외에도 여러 데이터가 사용될 수 있습니다.

## **1.3. 추천 시스템의 유형**

추천 시스템의 유형은 바로 아래 파트에서 다룹니다. **콘텐츠 기반 필터링**, **협업 필터링**(**최근접 이웃 협업 필터링**, **잠재 요인 협업 필터링**)이 있습니다. 대부분의 온라인 스토어에서는 잠재 요인 협업 필터링을 사용하지만 최근에는 개인화 특성을 더 강화할 목적으로 하이브리드 형식(콘텐츠 기반 필터링 + 협업 기반 필터링)을 사용하는 경우도 많아지는 추세입니다.

기실 **4.3. 확률적 경사 하강법을 이용한 행렬 분해** 파트까지는 아래 정리본보다 본서와 [링크1](https://hipster4020.tistory.com/109), [링크2](https://big-dream-world.tistory.com/61?category=470634)에 더 상세하게 설명되어 있습니다. 공부 흔적을 남길 목적이므로 핵심 내용만 정리하겠습니다.

# **2. 콘텐츠 기반 필터링 추천 시스템**

**콘텐츠 기반 필터링(Content Based Filtering)**은 사용자가 특정 아이템을 선호하는 경우에 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식입니다. 예컨대 사용자가 특정 영화에 높은 평점을 줬다면 그 영화의 장르, 배우, 감독, 영화 키워드 등 콘텐츠와 유사한 영화를 추천합니다. 

추천 시스템의 초창기에 주로 사용된 방식이지만 아이템 특성에 따라 여전히 많이 사용됩니다. 

# **3. 최근접 이웃 협업 필터링**

먼저 **협업 필터링(Collaborative Filtering)**에 대해 살펴볼 필요가 있습니다. 이 방식은 사용자 행동 양식(User Behavior)만을 토대로 추천합니다. 사용자 행동 양식이란 사용자가 아이템에 부여한 평점이나 상품 구매 이력 등을 예로 들 수 있습니다.

협업 필터링은 **사용자-아이템 평점 매트릭스(행렬)**처럼 축적된 사용자 행동 데이터를 토대로 사용자가 아직 평가하지 않은 아이템을 예측 평가(Predicted Rating) 하는 것이 주목표입니다. 사용자-아이템 평점 행렬은 많은 아이템을 열로 가진 다차원 행렬이며, 사용자가 평점을 매기는 경우가 많지 않으므로 희소 행렬입니다. 예컨대 사용자(행, Row)가 아이템 1 ~ 4(열, Column) 중에 아이템 1과 아이템 3만 평점을 부여했다면 이 평점들을 토대로 아이템 4의 평점을 예측 평가 합니다.

**최근접 이웃 협업 필터링(Nearest Neighbor Collaborative Filtering)**은 **메모리(Memory) 협업 필터링**으로도 불립니다. 여기서 아래 두 기반으로 나뉩니다.

- **사용자 기반(User-User)**: 당신과 비슷한 고객들이 다음 상품도 선택했습니다.

- **아이템 기반(Item-Item)**: 이 상품을 선택한 다른 고객들은 다음 상품도 선택했습니다.

첫 번째로, 사용자 기반 방식은 특정 사용자와 비슷한 다른 사용자를 TOP-N으로 선정하고, 이 TOP-N 사용자가 좋아하는 아이템을 추천합니다. 특정 사용자와 다른 사용자 간 유사도(Similarity)를 측정하여 가장 높은 유사도를 가진 TOP-N 사용자를 추출하고 선호하는 아이템을 추천하는 것입니다. 예컨대 사용자 1 ~ 3 중에 사용자 1에게 아이템을 추천하는 경우 사용자 3보다 사용자 2가 사용자 1과 비슷하게 평점을 부여했다면, 사용자 2가 사용한 아이템을 사용자 1에게 추천합니다.

참고로 유사도 측정에는 텍스트 분석에 사용되는 코사인 유사도가 가장 많이 사용됩니다. 추천 시스템에 사용되는 데이터 또한 텍스트 데이터처럼 희소 행렬이기 때문입니다.

두 번째로, 아이템 기반 방식은 아이템이 가지는 속성과는 무관하게 사용자가 특정 아이템을 선호하는지 여부(평점을 어떻게 부여했는지)가 추천 기준입니다. 사용자 기반 방식과 다르게 사용자-아이템 평점 행렬의 행과 열이 반대 형태입니다. 행이 아이템이고 열이 사용자인 것입니다. 예컨대 여러 사용자가 부여한 아이템 1 ~ 3의 평점 중에 아이템 1과 2의 평점이 아이템 3의 평점보다 유사하다면 사용자에게 아이템 2를 추천합니다.

대개 두 방식 중에 아이템 기반 방식이 더 높은 정확도를 보이며 대부분 활용됩니다. 사용자 기반 방식은 거의 사용되지 않습니다. 비슷한 아이템을 선호하거나 선택한다고 모든 사용자의 취향이 비슷하다고 단정하기엔 근거가 미약합니다. 유행을 타거나 유명한 아이템의 경우 취향과 무관하게 많은 사용자가 선택하기도 합니다. 더욱이 사용자들이 평점을 부여한 아이템의 경우 대체적으로 평점을 부여한 빈도가 많지 않은데 이를 토대로 유사도를 비교하는 것은 다소 무리가 있습니다.

최근접 이웃 협업 필터링은 콘텐츠 기반 필터링처럼 추천 시스템의 초창기에 주로 사용된 방식이지만 아이템 특성에 따라 여전히 많이 사용됩니다. 특히 아마존은 아이템 기반의 최근접 이웃 협업 필터링을 추천 엔진으로 사용합니다.

# **4. 잠재 요인 협업 필터링**

## **4.1. 잠재 요인 협업 필터링의 이해**

**잠재 요인 협업 필터링(Latent Factor Collaborative Filtering)**은 사용자-아이템 평점 행렬에 있는 잠재 요인을 추출하여 추천 예측을 수행하는 기법입니다. 잠재 요인은 **행렬 분해(Matrix Factorization)** 기법을 활용하여 대규모 다차원 행렬을 **SVD(Singular Value Decomposition, 특이값 분해)** 같은 차원 감소 기법으로 분해하는 과정에서 추출합니다. 즉 잠재 요인 협업 필터링은 행렬 분해 기법을 기반으로 합니다.

잠재 요인을 명확하게 정의내릴 순 없지만 이 잠재 요인을 기반으로 사용자-아이템 평점 행렬을 저차원 밀집 행렬인 **사용자-잠재 요인 행렬**과 아이템-잠재 요인 매트릭스의 전치 행렬인 **잠재 요인-아이템 행렬**로 분해할 수 있습니다. 두 행렬을 내적하여 새로운 예측 사용자-아이템 평점 행렬 데이터를 생성하고 사용자가 평점을 부여하지 않은 아이템에 예측 평점을 부여하는 것이 잠재 요인 협력 필터링의 핵심입니다.

행렬 분해를 거쳐 추출되는 잠재 요인이 무엇을 의미하는지는 알 수 없습니다. 다만 영화 평점 기반의 사용자-아이템 평점 행렬이라면 장르별 특성 선호도 정도로 가정할 수 있습니다. 사용자-잠재 요인 행렬은 영화 장르 선호도, 아이템-잠재 요인 행렬은 장르별 특성값으로 정의할 수 있습니다. 본서와 [링크](https://ariz1623.tistory.com/228)에서 이 가정에 대하여 그림과 함께 메커니즘을 설명합니다.

## **4.2. 행렬 분해의 이해**

행렬 분해와 예측 평점 도출에 대한 원리는 본서와 [링크](https://big-dream-world.tistory.com/69)를 참고하시기 바랍니다.

참고로 행렬 분해는 주로 SVD를 이용하지만 Null 값이 존재하는 행렬에는 적용할 수 없습니다. 이런 경우 **SGD(Stochastic Gradient Descent, 확률적 경사 하강법)**나 **ALS(Alternating Least Squares, 교대 최소 제곱법)**를 사용하여 SVD를 수행합니다.

## **4.3. 확률적 경사 하강법을 이용한 행렬 분해**

확률적 경사 하강법을 이용한 행렬 분해의 원리는 본서와 [링크](https://big-dream-world.tistory.com/69)를 참고하시기 바랍니다.

일반적으로 사용자-아이템 평점 행렬은 행렬 분해를 위해 단순히 예측 오류값의 최소화와 학습 시 과적합을 피하기 위해 규제를 반영한 비용 함수를 적용합니다. L2 규제를 반영하여 실제 R 행렬 값과 예측 R 행렬 값의 차이를 최소화하는 방향성을 가지고 P 행렬과 Q 행렬에 적절한 값을 반복적으로 업데이트하면서 최적화된 예측 R 행렬을 구하는 방식이 SGD 기반 행렬 분해입니다.만족할 만한 오류값을 가질 때까지 작업을 반복하면서 P와 Q 값을 근사화합니다.

SGD를 토대로 행렬 분해를 수행해 보겠습니다. 분해할 원본 행렬 R을 행렬 P와 행렬 R로 분해하고 다시 $P \times Q.T$로 예측 행렬을 생성하겠습니다. 수행 과정이 다소 복잡해 보일 수 있으므로 가볍게 살피고 넘어가도 좋습니다. 

In [1]:
import numpy as np

# 원본 행렬 R을 생성합니다. 
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN ],
              [np.NaN, 5, np.NaN, 3, 1 ],
              [np.NaN, np.NaN, 3, 4, 4 ],
              [5, 2, 1, 2, np.NaN ]])
# 행은 사용자, 열은 아이템으로 지정합니다.
num_users, num_items = R.shape
# 잠재 요인의 차원 K는 3으로 설정합니다. 
K=3
# 분해 행렬인 P와 Q의 크기를 지정하고 정규분포를 가진 무작위 값으로 부여합니다. 
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

원본 행렬 R과 예측 행렬간 오차를 도출하는 새 함수를 선언하겠습니다. 이 함수는 원본 행렬 R에서 Null 값이 아닌 행렬 값의 인덱스를 추출하여 이 인덱스에 있는 행렬 R의 값과 분해된 행렬 P와 Q를 이용하여 다시 조합된 예측 행렬 값의 RMSE 값을 반환합니다.

In [6]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 분해된 행렬 P와 Q.T를 내적하여 예측 행렬 R을 도출합니다.
    full_pred_matrix = np.dot(P, Q.T)
    
    # 원본 행렬 R에서 Null 값이 아닌 값의 인덱스를 추출하여
    # 원본 행렬 R과 예측 행렬의 RMSE를 추출합니다.
    x_non_zero_index = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_index = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_index, y_non_zero_index]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_index, y_non_zero_index]
      
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

SGD 기법을 기반으로 행렬 분해를 수행하겠습니다. 먼저 행렬 R에서 Null 값을 제외한 데이터의 행렬 인덱스를 추출합니다.

In [7]:
# R > 0인 행 인덱스, 열 인덱스, 값을 `non_zeros` 리스트에 저장합니다. 
non_zeros = [(i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0]

# SGD를 반복해서 업데이트할 횟수를 지정합니다.
steps = 1000
# SGD의 학습률을 지정합니다.
learning_rate = 0.01
# L2 규제 계수를 지정합니다.
r_lambda = 0.01

# SGD 방식을 토대로 행렬 P와 행렬 Q를 계속 업데이트합니다. 
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값을 구합니다.
        eij = r - np.dot(P[i, :], Q[j, :].T)
        # 규제를 반영한 SGD 업데이트를 적용합니다.
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i,:])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j,:])

    rmse = get_rmse(R, P, Q, non_zeros)
    # 50회 반복할 때마다 오류 값을 출력합니다.
    if (step % 50) == 0:
        print("# iteration step:", step, "| rmse:", rmse)

# iteration step: 0 | rmse: 0.016410959588961445
# iteration step: 50 | rmse: 0.01637308966218993
# iteration step: 100 | rmse: 0.016333882336881784
# iteration step: 150 | rmse: 0.016293661274599174
# iteration step: 200 | rmse: 0.01625272572302336
# iteration step: 250 | rmse: 0.016211338984681307
# iteration step: 300 | rmse: 0.016169725523756753
# iteration step: 350 | rmse: 0.016128072491623933
# iteration step: 400 | rmse: 0.016086533303745463
# iteration step: 450 | rmse: 0.016045231961723017
# iteration step: 500 | rmse: 0.016004267423347165
# iteration step: 550 | rmse: 0.015963717671935662
# iteration step: 600 | rmse: 0.01592364333325902
# iteration step: 650 | rmse: 0.015884090797210332
# iteration step: 700 | rmse: 0.01584509485896164
# iteration step: 750 | rmse: 0.015806680922219037
# iteration step: 800 | rmse: 0.01576886681829548
# iteration step: 850 | rmse: 0.015731664296432853
# iteration step: 900 | rmse: 0.0156950802377121
# iteration step: 950 | rmse: 0.015659117

예측 행렬을 생성해 보겠습니다.

In [10]:
pred_matrix = np.dot(P, Q.T)
print('원본 행렬:\n', R)
print()
print('예측 행렬:\n', np.round(pred_matrix, 3))

원본 행렬:
 [[ 4. nan nan  2. nan]
 [nan  5. nan  3.  1.]
 [nan nan  3.  4.  4.]
 [ 5.  2.  1.  2. nan]]

예측 행렬:
 [[3.991 1.171 1.266 2.    1.649]
 [6.288 4.978 0.896 2.983 1.003]
 [6.401 0.866 2.987 3.978 3.986]
 [4.969 2.005 1.006 2.013 1.258]]


두 행렬의 값은 큰 차이가 없습니다. Null 값은 예측값으로 채워졌습니다.

# **5. 콘텐츠 기반 필터링 실습 - TMDB 5000 영화 데이터 세트**

캐글의 [TMDB 5000 영화 데이터 세트](https://www.kaggle.com/tmdb/tmdb-movie-metadata)에서 파일을 다운로드하여 콘텐츠 기반 필터링을 실습해 보겠습니다. 

## **5.1. 장르 속성을 이용한 영화 콘텐츠 기반 필터링**

콘텐츠 기반 필터링은 사용자가 특정 영화를 감상하고 그 영화를 좋아했다면 비슷한 특성이나 속성, 구성 요소 등을 가진 다른 영화를 추천하는 방식입니다. 예컨대 액션 장르인 영화 A를 재미있게 봤다면 해당하는 장르 중에 높은 평점을 받은 다른 영화를 추천하거나 영화 A를 제작한 감독의 다른 영화를 추천합니다. 다양한 콘텐츠(장르, 감독, 배우, 평점, 키워드, 영화 설명)는 영화(아이템, 상품, 서비스 등) 간 유사성을 판단하는 기준입니다.

콘텐츠 기반 필터링 추천 시스템을 영화 장르 속성을 기반으로 생성해 보겠습니다. 장르 피처 값의 유사도를 비교하여 높은 평점을 가진 영화를 추천하는 시스템입니다.

## **5.2. 데이터 로딩 및 가공**

In [11]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [18]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

movies = pd.read_csv('/content/gdrive/MyDrive/tmdb_5000/tmdb_5000_movies.csv')
display(movies.head(3))
print(movies.shape)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466

(4803, 20)


콘텐츠 기반 필터링 추천 분석에 적합한 피처만 추출하여 새 데이터프레임으로 정리하겠습니다.

In [19]:
movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]
movies_df.head(3)

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...

결측치를 확인해 보겠습니다.

In [20]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            4803 non-null   int64  
 1   title         4803 non-null   object 
 2   genres        4803 non-null   object 
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64  
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   object 
 7   overview      4800 non-null   object 
dtypes: float64(2), int64(2), object(4)
memory usage: 300.3+ KB




---

고민 중

---



## **5.3. 장르 콘텐츠 유사도 측정**

## **5.4. 장르 콘텐츠 필터링을 이용한 영화 추천**

# **6. 아이템 기반 최근접 이웃 협업 필터링 실습**

## **6.1. 데이터 가공 및 변환**

## **6.2. 영화 간 유사도 산출**

## **6.3. 아이템 기반 최근접 이웃 협업 필터링으로 개인화된 영화 추천**

# **7. 행렬 분해를 이용한 잠재 요인 협업 필터링 실습**

# **8. 파이썬 추천 시스템 패키지 - Surprise**

## **8.1. Surprise 패키지 소개**

## **8.2. Surprise를 이용한 추천 시스템 구축**

## **8.3. Surprise 주요 모듈 소개**

### **8.3.1. Dataset**

### **8.3.2. OS 파일 데이터를 Surprise 데이터 세트로 로딩**

### **8.3.3. 판다스 DataFrame에서 Surprise 데이터 세트로 로딩**

## **8.4. Surprise 추천 알고리즘 클래스**

## **8.5. 베이스라인 평점**

## **8.6. 교차 검증과 하이퍼 파라미터 튜닝**

## **8.7. Surprise를 이용한 개인화 영화 추천 시스템 구축**

# **9. 정리**